monitored_experiments:
  # NOTE: Add more or comment out the experiments you want to monitor below

  # baseline
  sit-xl-base-50k:
    projector_embed_dims: 768
    model: SiT-XL/2

  # REPA
  sit-xl-linear-dinov2-b-enc8-50k:
    projector_embed_dims: 768
    model: SiT-XL/2

  # REPA + patch2patch
  sit-xl-linear-dinov2-b-enc8-patch2patch-0.2-0.2-coeff0.2-50k:
    projector_embed_dims: 768
    model: SiT-XL/2

  # REPA + sample2sample
  sit-xl-linear-dinov2-b-enc8-sample2sample-0.2-0.2-coeff0.2-50k:
    projector_embed_dims: 768
    model: SiT-XL/2

  # patch2patch
  sit-xl-linear-dinov2-b-enc8-patch2patch-0.2-0.2-only-coeff0.2-50k:
    projector_embed_dims: 768
    model: SiT-XL/2

  # sample2sample
  sit-xl-linear-dinov2-b-enc8-sample2sample-0.2-0.2-only-coeff0.2-50k:
    projector_embed_dims: 768
    model: SiT-XL/2

  # REPA + patch2patch_jsd
  sit-xl-linear-dinov2-b-enc8-patch2patch-jsd-0.2-0.2-coeff0.2-50k:
    projector_embed_dims: 768
    model: SiT-XL/2

  # patch2patch_jsd
  sit-xl-linear-dinov2-b-enc8-patch2patch-jsd-0.2-0.2-only-coeff0.2-50k:
    projector_embed_dims: 768
    model: SiT-XL/2

  # REPA + sample2sample_jsd
  sit-xl-linear-dinov2-b-enc8-sample2sample-jsd-0.2-0.2-coeff0.2-50k:
    projector_embed_dims: 768
    model: SiT-XL/2

  # sample2sample_jsd
  sit-xl-linear-dinov2-b-enc8-sample2sample-jsd-0.2-0.2-only-coeff0.2-50k:
    projector_embed_dims: 768
    model: SiT-XL/2

  # sample2sample_jsd + keepdiag
  sit-xl-linear-dinov2-b-enc8-sample2sample-jsd-0.2-0.2-only-coeff0.2-keepdiag-50k:
    projector_embed_dims: 768
    model: SiT-XL/2
